#%RAML 1.0 DataType
description: "this is product data type"

type: object
properties:
  productid:
    type: string
    required: true
  productsize:
    type: integer
    required: false
  productcost:
    type: string
    required: false

